linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - revive

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
