package tokens

import "strings"

// Config holds all dialect-specific tokenizer settings.
// Build one with DefaultConfig() then override fields for your dialect.
// Call BuildTrie() after modifying Keywords, Comments, Quotes, or Identifiers.
type Config struct {
	SingleTokens                    map[string]TokenType
	Keywords                        map[string]TokenType
	Quotes                          map[string]string // open → close
	Identifiers                     map[string]string // open → close
	Comments                        map[string]string // start → end ("" for line comments)
	StringEscapes                   map[string]struct{}
	IdentifierEscapes               map[string]struct{}
	NestedComments                  bool
	HintStart                       string
	TokensPrecedingHint             map[TokenType]struct{}
	Commands                        map[TokenType]struct{}
	CommandPrefixTokens             map[TokenType]struct{}
	NumbersCanBeUnderscoreSeparated bool
	IdentifiersCanStartWithDigit    bool
	KeywordTrie                     Trie
}

// BuildTrie populates KeywordTrie from the current maps.
// Call after any map change.
func (cfg *Config) BuildTrie() {
	var keys []string
	for k := range cfg.Keywords {
		if strings.ContainsRune(k, ' ') || anySingleIn(k, cfg.SingleTokens) {
			keys = append(keys, strings.ToUpper(k))
		}
	}
	for k := range cfg.Comments {
		keys = append(keys, strings.ToUpper(k))
	}
	for k := range cfg.Quotes {
		keys = append(keys, strings.ToUpper(k))
	}
	for k := range cfg.Identifiers {
		keys = append(keys, strings.ToUpper(k))
	}
	cfg.KeywordTrie = NewTrie(keys)
}

func anySingleIn(s string, m map[string]TokenType) bool {
	for _, ch := range s {
		if _, ok := m[string(ch)]; ok {
			return true
		}
	}
	return false
}

// DefaultConfig returns the base tokenizer configuration matching
// Python sqlglot's Tokenizer class defaults (tokens.py).
func DefaultConfig() Config {
	cfg := Config{
		SingleTokens: map[string]TokenType{
			"(": LParen,
			")": RParen,
			"[": LBracket,
			"]": RBracket,
			"{": LBrace,
			"}": RBrace,
			"&": Amp,
			"^": Caret,
			":": Colon,
			",": Comma,
			".": Dot,
			"-": Dash,
			"=": Eq,
			">": Gt,
			"<": Lt,
			"%": Mod,
			"!": Not,
			"|": Pipe,
			"+": Plus,
			";": Semicolon,
			"/": Slash,
			`\`: Backslash,
			"*": Star,
			"~": Tilde,
			"?": Placeholder,
			"@": Parameter,
			"#": Hash,
		},
		Quotes:            map[string]string{"'": "'"},
		Identifiers:       map[string]string{`"`: `"`},
		Comments:          map[string]string{"--": "", "/*": "*/"},
		StringEscapes:     map[string]struct{}{"'": {}},
		IdentifierEscapes: map[string]struct{}{},
		NestedComments:    true,
		HintStart:         "/*+",
		TokensPrecedingHint: map[TokenType]struct{}{
			Select: {}, Insert: {}, Update: {}, Delete: {},
		},
		Commands: map[TokenType]struct{}{
			Command: {}, Execute: {}, Fetch: {}, Show: {}, Rename: {},
		},
		CommandPrefixTokens: map[TokenType]struct{}{
			Semicolon: {}, Begin: {},
		},
		Keywords: defaultKeywords(),
	}
	cfg.BuildTrie()
	return cfg
}

func defaultKeywords() map[string]TokenType {
	return map[string]TokenType{
		// Multi-char operators
		"/*+": Hint,
		"&<":  AmpLt,
		"&>":  AmpGt,
		"==":  Eq,
		"::":  DColon,
		"?::": QDColon,
		"||":  DPipe,
		"|>":  PipeGt,
		">=":  Gte,
		"<=":  Lte,
		"<>":  Neq,
		"!=":  Neq,
		":=":  ColonEq,
		"<=>": NullsafeEq,
		"->":  Arrow,
		"->>": DArrow,
		"=>":  FArrow,
		"#>":  HashArrow,
		"#>>": DHashArrow,
		"<->": LRArrow,
		"&&":  DAmp,
		"??":  DQMark,
		"~~~": Glob,
		"~~":  Like,
		"~~*": Ilike,
		"~*":  IRLike,
		"-|-": Adjacent,
		// SQL keywords
		"ALL":               All,
		"AND":               And,
		"ANTI":              Anti,
		"ANY":               Any,
		"ASC":               Asc,
		"AS":                Alias,
		"ASOF":              Asof,
		"AUTOINCREMENT":     AutoIncrement,
		"AUTO_INCREMENT":    AutoIncrement,
		"BEGIN":             Begin,
		"BETWEEN":           Between,
		"CACHE":             Cache,
		"UNCACHE":           UnCache,
		"CASE":              Case,
		"CHARACTER SET":     CharacterSet,
		"CLUSTER BY":        ClusterBy,
		"COLLATE":           Collate,
		"COLUMN":            Column,
		"COMMIT":            Commit,
		"CONNECT BY":        ConnectBy,
		"CONSTRAINT":        Constraint,
		"COPY":              Copy,
		"CREATE":            Create,
		"CROSS":             Cross,
		"CUBE":              Cube,
		"CURRENT_DATE":      CurrentDate,
		"CURRENT_SCHEMA":    CurrentSchema,
		"CURRENT_TIME":      CurrentTime,
		"CURRENT_TIMESTAMP": CurrentTimestamp,
		"CURRENT_USER":      CurrentUser,
		"CURRENT_CATALOG":   CurrentCatalog,
		"DATABASE":          Database,
		"DEFAULT":           Default,
		"DELETE":            Delete,
		"DESC":              Desc,
		"DESCRIBE":          Describe,
		"DISTINCT":          Distinct,
		"DISTRIBUTE BY":     DistributeBy,
		"DIV":               Div,
		"DROP":              Drop,
		"ELSE":              Else,
		"END":               End,
		"ENUM":              Enum,
		"ESCAPE":            Escape,
		"EXCEPT":            Except,
		"EXECUTE":           Execute,
		"EXISTS":            Exists,
		"FALSE":             False,
		"FETCH":             Fetch,
		"FILTER":            Filter,
		"FILE":              File,
		"FIRST":             First,
		"FULL":              Full,
		"FUNCTION":          Function,
		"FOR":               For,
		"FOREIGN KEY":       ForeignKey,
		"FORMAT":            Format,
		"FROM":              From,
		"GEOGRAPHY":         Geography,
		"GEOMETRY":          Geometry,
		"GLOB":              Glob,
		"GROUP BY":          GroupBy,
		"GROUPING SETS":     GroupingSets,
		"HAVING":            Having,
		"ILIKE":             Ilike,
		"IN":                In,
		"INDEX":             Index,
		"INET":              Inet,
		"INNER":             Inner,
		"INSERT":            Insert,
		"INTERVAL":          Interval,
		"INTERSECT":         Intersect,
		"INTO":              Into,
		"IS":                Is,
		"ISNULL":            IsNull,
		"JOIN":              Join,
		"KEEP":              Keep,
		"KILL":              Kill,
		"LATERAL":           Lateral,
		"LEFT":              Left,
		"LIKE":              Like,
		"LIMIT":             Limit,
		"LOAD":              Load,
		"LOCALTIME":         LocalTime,
		"LOCALTIMESTAMP":    LocalTimestamp,
		"LOCK":              Lock,
		"MERGE":             Merge,
		"NAMESPACE":         Namespace,
		"NATURAL":           Natural,
		"NEXT":              Next,
		"NOT":               Not,
		"NOTNULL":           NotNull,
		"NULL":              Null,
		"OBJECT":            Object,
		"OFFSET":            Offset,
		"ON":                On,
		"OR":                Or,
		"XOR":               Xor,
		"ORDER BY":          OrderBy,
		"ORDINALITY":        Ordinality,
		"OUT":               Out,
		"OUTER":             Outer,
		"OVER":              Over,
		"OVERLAPS":          Overlaps,
		"OVERWRITE":         Overwrite,
		"PARTITION":         Partition,
		"PARTITION BY":      PartitionBy,
		"PARTITIONED BY":    PartitionBy,
		"PARTITIONED_BY":    PartitionBy,
		"PERCENT":           Percent,
		"PIVOT":             Pivot,
		"PRAGMA":            Pragma,
		"PRIMARY KEY":       PrimaryKey,
		"PROCEDURE":         Procedure,
		"OPERATOR":          Operator,
		"QUALIFY":           Qualify,
		"RANGE":             Range,
		"RECURSIVE":         Recursive,
		"REGEXP":            RLike,
		"RENAME":            Rename,
		"REPLACE":           Replace,
		"RETURNING":         Returning,
		"REFERENCES":        References,
		"RIGHT":             Right,
		"RLIKE":             RLike,
		"ROLLBACK":          Rollback,
		"ROLLUP":            Rollup,
		"ROW":               Row,
		"ROWS":              Rows,
		"SCHEMA":            Schema,
		"SELECT":            Select,
		"SEMI":              Semi,
		"SESSION":           SessionToken,
		"SESSION_USER":      SessionUser,
		"SET":               Set,
		"SETTINGS":          Settings,
		"SHOW":              Show,
		"SIMILAR TO":        SimilarTo,
		"SOME":              Some,
		"SORT BY":           SortBy,
		"SQL SECURITY":      SQLSecurity,
		"START WITH":        StartWith,
		"STRAIGHT_JOIN":     StraightJoin,
		"TABLE":             Table,
		"TABLESAMPLE":       TableSample,
		"TEMP":              Temporary,
		"TEMPORARY":         Temporary,
		"THEN":              Then,
		"TRUE":              True,
		"TRUNCATE":          Truncate,
		"TRIGGER":           Trigger,
		"UNION":             Union,
		"UNKNOWN":           Unknown,
		"UNNEST":            Unnest,
		"UNPIVOT":           UnPivot,
		"UPDATE":            Update,
		"USE":               Use,
		"USING":             Using,
		"UUID":              UUID,
		"VALUES":            Values,
		"VIEW":              View,
		"VOLATILE":          Volatile,
		"WHEN":              When,
		"WHERE":             Where,
		"WINDOW":            Window,
		"WITH":              With,
		"APPLY":             Apply,
		"ARRAY":             Array,
		"BIT":               Bit,
		"BOOL":              Boolean,
		"BOOLEAN":           Boolean,
		"BYTE":              TinyInt,
		"MEDIUMINT":         MediumInt,
		"INT1":              TinyInt,
		"TINYINT":           TinyInt,
		"INT16":             SmallInt,
		"SHORT":             SmallInt,
		"SMALLINT":          SmallInt,
		"HUGEINT":           Int128,
		"UHUGEINT":          UInt128,
		"INT2":              SmallInt,
		"INTEGER":           Int,
		"INT":               Int,
		"INT4":              Int,
		"INT32":             Int,
		"INT64":             BigInt,
		"INT128":            Int128,
		"INT256":            Int256,
		"LONG":              BigInt,
		"BIGINT":            BigInt,
		"INT8":              TinyInt,
		"UINT":              UInt,
		"UINT128":           UInt128,
		"UINT256":           UInt256,
		"DEC":               Decimal,
		"DECIMAL":           Decimal,
		"DECIMAL32":         Decimal32,
		"DECIMAL64":         Decimal64,
		"DECIMAL128":        Decimal128,
		"DECIMAL256":        Decimal256,
		"DECFLOAT":          DecFloat,
		"BIGDECIMAL":        BigDecimal,
		"BIGNUMERIC":        BigDecimal,
		"BIGNUM":            BigNum,
		"LIST":              List,
		"MAP":               Map,
		"NULLABLE":          Nullable,
		"NUMBER":            Decimal,
		"NUMERIC":           Decimal,
		"FIXED":             Decimal,
		"REAL":              Float,
		"FLOAT":             Float,
		"FLOAT4":            Float,
		"FLOAT8":            Double,
		"DOUBLE":            Double,
		"DOUBLE PRECISION":  Double,
		"JSON":              JSON,
		"JSONB":             JSONB,
		"CHAR":              Char,
		"CHARACTER":         Char,
		"CHAR VARYING":      VarChar,
		"CHARACTER VARYING": VarChar,
		"NCHAR":             NChar,
		"VARCHAR":           VarChar,
		"VARCHAR2":          VarChar,
		"NVARCHAR":          NVarChar,
		"NVARCHAR2":         NVarChar,
		"BPCHAR":            BPChar,
		"STR":               Text,
		"STRING":            Text,
		"TEXT":              Text,
		"LONGTEXT":          LongText,
		"MEDIUMTEXT":        MediumText,
		"TINYTEXT":          TinyText,
		"CLOB":              Text,
		"LONGVARCHAR":       Text,
		"BINARY":            Binary,
		"BLOB":              VarBinary,
		"LONGBLOB":          LongBlob,
		"MEDIUMBLOB":        MediumBlob,
		"TINYBLOB":          TinyBlob,
		"BYTEA":             VarBinary,
		"VARBINARY":         VarBinary,
		"TIME":              Time,
		"TIMETZ":            TimeTZ,
		"TIME_NS":           TimeNS,
		"TIMESTAMP":         Timestamp,
		"TIMESTAMPTZ":       TimestampTZ,
		"TIMESTAMPLTZ":      TimestampLTZ,
		"TIMESTAMP_LTZ":     TimestampLTZ,
		"TIMESTAMPNTZ":      TimestampNTZ,
		"TIMESTAMP_NTZ":     TimestampNTZ,
		"DATE":              Date,
		"DATETIME":          DateTime,
		"INT4RANGE":         Int4Range,
		"INT4MULTIRANGE":    Int4MultiRange,
		"INT8RANGE":         Int8Range,
		"INT8MULTIRANGE":    Int8MultiRange,
		"NUMRANGE":          NumRange,
		"NUMMULTIRANGE":     NumMultiRange,
		"TSRANGE":           TSRange,
		"TSMULTIRANGE":      TSMultiRange,
		"TSTZRANGE":         TSTZRange,
		"TSTZMULTIRANGE":    TSTZMultiRange,
		"DATERANGE":         DateRange,
		"DATEMULTIRANGE":    DateMultiRange,
		"UNIQUE":            Unique,
		"VECTOR":            Vector,
		"STRUCT":            Struct,
		"SEQUENCE":          Sequence,
		"VARIANT":           Variant,
		"ALTER":             Alter,
		"ANALYZE":           Analyze,
		"CALL":              Command,
		"COMMENT":           Comment,
		"EXPLAIN":           Command,
		"GRANT":             Grant,
		"REVOKE":            Revoke,
		"OPTIMIZE":          Command,
		"PREPARE":           Command,
		"VACUUM":            Command,
		"USER-DEFINED":      UserDefined,
		"FOR VERSION":       VersionSnapshot,
		"FOR TIMESTAMP":     TimestampSnapshot,
	}
}
